### ISSUE TITLE
Binaries for Raspberry Pi

### ISSUE THREAD

**Issue by ipsecguy** [jayme-github/fritzbox_smarthome_exporter#12]
Thanks for your great work, worked immediatly!

Could you also create the binaries for Raspberry Pi (armv6 for Raspberry Pi Zero I believe)?

Andreas

**Comment by jayme-github** [comment]
I've not actually tested the binaries/docker images but armv6 and armv7 will now be included in releases starting from [v0.4.3](https://github.com/jayme-github/fritzbox_smarthome_exporter/releases/tag/v0.4.3)
