### ISSUE TITLE
target is up but no data points

### ISSUE THREAD

**Issue by petettx** [jayme-github/fritzbox_smarthome_exporter#2]
Hi,

i recently set up a prometheus server and using the fritzbox_smarthome_exporter.
my prometheus.yml looks like this:
`- job_name: 'fritzbox_smarthome_exporter'
    static_configs:
      - targets: ['localhost:9103']
`
I followed the instructions for fritzbox_smarthome_exporter and created a service. the status is up and logged in.

`Jul 14 13:54:30 grafana fritzbox_smarthome_exporter[1970]: 2019/07/14 13:54:30 Login successful`

on prometheus localhost:9090/targets the target is up and scraping seems to work:
localhost:9103/metrics | UP | instance="localhost:9103" | last scrape: 11.432s ago

`curl localhost:9103/metrics` gives me more than enough data. 

However on localhost:9090/graph it doesn't matter which metric I choose for testing, there no data present at all.

Can anyone point me to the way of debugging this issue?

**Comment by jayme-github** [comment]
Do you see the `fritzbox_*` metrics in `localhost:9103/metrics` (as in the README example)?
If that's the case (and the target is up in prometheus) metrics should be ingested into prometheus. Could you post a screenshot of what you want to do/query in prometheus?
