### ISSUE TITLE
Parsing error for devices that are not present

### ISSUE THREAD

**Issue by infofrs** [jayme-github/fritzbox_smarthome_exporter#4]
2020/06/11 11:36:20 Unable to parse temperature data of "XXX" : strconv.ParseFloat: parsing "": invalid syntax
2020/06/11 11:36:20 Unable to parse temperature offset data of "XXX" : strconv.ParseFloat: parsing "": invalid syntax
2020/06/11 11:36:20 Unable to parse energy data of "XXX" : strconv.ParseFloat: parsing "": invalid syntax
2020/06/11 11:36:20 Unable to parse power data of "XXX" : strconv.ParseFloat: parsing "": invalid syntax

Source: AVM 7490 / OS 7.12

**Comment by jayme-github** [comment]
Am I right to assume that all errors are for the same device?
Did you get data for this device in the past? Do you have different devices that still return data?

I'm running the same box and OS version currently without issues. Please double check if the account you are using has access so smarthome features.

**Comment by infofrs** [comment]
Checked on login is fine:
![image](https://user-images.githubusercontent.com/44997840/84750925-3bc99300-afbc-11ea-8f5a-b296406ed815.png)

The error accours during the first device:
![image](https://user-images.githubusercontent.com/44997840/84750822-13419900-afbc-11ea-8690-9f50a6474250.png)

I think the error accours if a device is not connected to the fritz.box but still running. The 2 error devices have the status "not connected" at the moment. May be they could excluded?

**Comment by infofrs** [comment]
Solved
You get the given error if one or more devices are not connected
![image](https://user-images.githubusercontent.com/44997840/84753865-daa3be80-afbf-11ea-83f4-5b326c9a8157.png)
Just reconnected them and all Device Datas are available in prometheus now. 

Thanks for your work.

**Comment by jayme-github** [comment]
Thanks for your report. I would classify this as a bug indeed. The exporter knows about the device being present or not (which I assume is "green or gray" ;-) ). As it seems that this means there will be no data for those four attributes, it should definitely not try to parse those.

I'll add a fix (and probably some tests) later on.

**Comment by infofrs** [comment]
Thanks! I just recreated a little Dashboard with multiple Values and works fine.
![prometheus_fritzbox](https://user-images.githubusercontent.com/44997840/84777949-8bbb5080-afe2-11ea-917f-b42d23e32bea.JPG)

**Comment by jayme-github** [comment]
I've pushed [v0.0.6](https://github.com/jayme-github/fritzbox_smarthome_exporter/releases/tag/v0.0.6) but did not had the chance to test that with real absent devices. If you are able to, please let me know if that fixes the issue.
