### ISSUE TITLE
Possible external monitoring?

### ISSUE THREAD

**Issue by Surfer2010** [jayme-github/fritzbox_smarthome_exporter#5]
Hello,
is IT possible to Monitor the fb from an external Server? So i can get notified once the fb is offline or having trouble of any kind?

**Comment by jayme-github** [comment]
The exporter is designed to run on a second machine (e.g. not on the FritzBox itself) so you get that by default. As per Prometheus best practice the exporter provides a `up` gauge metric which will be set to `0` in case of connection (or any other fatal) failure.

**Comment by Surfer2010** [comment]
> The exporter is designed to run on a second machine (e.g. not on the FritzBox itself) so you get that by default. As per Prometheus best practice the exporter provides a `up` gauge metric which will be set to `0` in case of connection (or any other fatal) failure.

I know, but is it possible to do so from "external" so over the internet so get messaged if the FB is "offline" kind of?

**Comment by jayme-github** [comment]
You would have to make the FritzBox interface accessible to whatever external system you want to scrape it from. While that is definitely possible I would not recommend it.
