### ISSUE TITLE
Energy consumption over a certain time range

### ISSUE THREAD

**Issue by BroderPeters** [jayme-github/fritzbox_smarthome_exporter#6]
First of all: Thanks for this nice and smooth project!

I have a general question: While coming up with the project did you ever thought about being able to display the energy consumption on an e.g. monthly level?

Before I found this project I was planning to display my energy usage on a daily and/or monthly level but couldn't think of a proper way with Prometheus (probably because I'm not that experienced with it).
Although I think that it's nice to know how much you have used in general I'm worried that the value will lose its worth over time as it just grows bigger and bigger. E.g. I would just like to know it on an annual base to better predict my energy bills.

**Comment by jayme-github** [comment]
Thanks.
Guess that's more of a general prometheus question than related to this exporter. Maybe this article is of interest:
https://www.robustperception.io/monthly-reporting-with-prometheus-and-python
