### ISSUE TITLE
armhf and arm64 version

### ISSUE THREAD

**Issue by b2un0** [jayme-github/fritzbox_smarthome_exporter#7]
thanks for your great work, but can you please build also docker images for armhf and arm64?

**Comment by jayme-github** [comment]
Sure, https://github.com/jayme-github/fritzbox_smarthome_exporter/releases/tag/v0.0.8 has them

**Comment by b2un0** [comment]
thank you, but this are only the binaries.
the docker image are still only a amd64 image

you can build simple multi arch images with github workflows, like this:
https://github.com/b2un0/docker-netcup-dyndns/blob/master/.github/workflows/docker-release.yml

**Comment by jayme-github** [comment]
Oops, I must have looked over the docker part of your message.

I've bluntly re-tagged v0.0.8 and dockerhub now contains v0.0.8 linux images for 386, amd64, arm and arm64 (which I have not tested yet). Please feel free to report any issues you find.
