### ISSUE TITLE
nothing to show up

### ISSUE THREAD

**Issue by Hellangel1987** [jayme-github/fritzbox_smarthome_exporter#8]
Hi,

i just installed your Git and did the credentials - also it shows only "login successfull"

![image](https://user-images.githubusercontent.com/20953591/131344641-dd74f685-990f-4f6b-ab12-15e114a280cb.png)

any hint to get an log whats going wrong? 

The Prometeus is also not showing anything 

![image](https://user-images.githubusercontent.com/20953591/131344747-75ec8daa-fb7e-4644-959a-50fbb265b17c.png)

**Comment by jayme-github** [comment]
Hi,

you could  `curl localhost:9103/metrics` to check if the exporter actually returns data. If that's the case, please make sure that the exporter is configured as target in your prometheus config and that the target is actually scraped.

**Comment by Hellangel1987** [comment]
that worked thank you!
