### ISSUE TITLE
Add metric for humidity of DECT 440

### ISSUE THREAD

**Issue by CokaColaOase** [jayme-github/fritzbox_smarthome_exporter#9]
Great work, thank you! Would it be possible that you add a metric for the humidity sensor in the DECT 440 buttons? That would help me a lot. Thanks!

**Comment by jayme-github** [comment]
AIUI there currently is no support in fritzctl for that, see: https://github.com/bpicode/fritzctl/pull/237
That would need to be merged and tested (in a fork, potentially. As the project is unfortunately archived) before the exporter can support that.

**Comment by CokaColaOase** [comment]
Thanks for the prompt reply. I'm quite new to github, but AIUI the user who made that pull request made his own fork and added the humidity parameters there. Would this be helpful? [mkalus/fritzctl](https://github.com/mkalus/fritzctl)

**Comment by jayme-github** [comment]
Yes, that's a good starting point but as I don't own such a device I can't verify the work done there.

Can you, by chance, post a device list here with a DECT 440 paired? A command like `fritzctl --loglevel=debug manifest export > /dev/null` (the last fritzctl release binary is fine) should print a line containing the `devicelist` XML (something like this https://github.com/bpicode/fritzctl/blob/master/testdata/devicelist_fritzos06.83.xml). You may want to change the `identifier` attributes and `<name>...</name>` fields of the devices before posting (but please leave the rest intact.

**Comment by MatthiasFraass** [comment]
That seems to work:

```xml
<device identifier="FOOFAA" id="25" functionbitmask="1048864" fwversion="05.21" manufacturer="AVM" productname="FRITZ!DECT 440">
	<present>1</present><txbusy>0</txbusy>
	<name>Taster Wohnzimmer</name><battery>100</battery><batterylow>0</batterylow>
	<temperature><celsius>200</celsius><offset>0</offset></temperature>
	<humidity><rel_humidity>38</rel_humidity></humidity>
	<button identifier="FOOFAA-1" id="5000"><name>Taster Wohnzimmer: Oben rechts</name><lastpressedtimestamp>1643351645</lastpressedtimestamp></button>
	<button identifier="FOOFAA-3" id="5001"><name>Taster Wohnzimmer: Unten rechts</name><lastpressedtimestamp>1642844240</lastpressedtimestamp></button>
	<button identifier="FOOFAA-5" id="5002"><name>Taster Wohnzimmer: Unten links</name><lastpressedtimestamp>1642791540</lastpressedtimestamp></button>
	<button identifier="FOOFAA-7" id="5003"><name>Taster Wohnzimmer: Oben links</name><lastpressedtimestamp>1642763963</lastpressedtimestamp></button>
</device>
```

The <rel_humidity> has the right values.

**Comment by CokaColaOase** [comment]
Mine looks quite the same:

```
<devicelist version="1" fwversion="7.29">    
    <device identifier="FIZZ BUZZ" id="22" functionbitmask="1048864" fwversion="05.21" manufacturer="AVM" productname="FRITZ!DECT 440">
        <present>1</present><txbusy>0</txbusy>
        <name>Taster Bad</name>
        <battery>100</battery><batterylow>0</batterylow>
        <temperature><celsius>175</celsius><offset>0</offset></temperature>
        <humidity><rel_humidity>54</rel_humidity></humidity>
        <button identifier="FIZZ BUZZ-1" id="5008"><name>Taster Bad: Oben rechts</name><lastpressedtimestamp>1643533662</lastpressedtimestamp></button>
        <button identifier="FIZZ BUZZ-3" id="5009"><name>Taster Bad: Unten rechts</name><lastpressedtimestamp></lastpressedtimestamp></button>
        <button identifier="FIZZ BUZZ-5" id="5010"><name>Taster Bad: Unten links</name><lastpressedtimestamp></lastpressedtimestamp></button>
        <button identifier="FIZZ BUZZ-7" id="5011"><name>Taster Bad: Oben links</name><lastpressedtimestamp></lastpressedtimestamp></button>
    </device>   
</devicelist>
```

While you are at it, could you please also add the battery value to the output?

**Comment by jayme-github** [comment]
I've just released [v0.3.0-rc.1](https://github.com/jayme-github/fritzbox_smarthome_exporter/releases/tag/v0.3.0-rc.1). Please give it a try and let me know if it works for you.

**Comment by CokaColaOase** [comment]
I pulled the new image and have now the humidity values and battery charge levels available where I need them. Works for me perfectly, thank you so much!

**Comment by jayme-github** [comment]
> I pulled the new image and have now the humidity values and battery charge levels available where I need them. Works for me perfectly, thank you so much!

Happy to hear, thanks for testing.

**Comment by MatthiasFraass** [comment]
It worked instantly and you even have standardized the battery level.
Thank you very much!
